
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jhonatan
 */
public class RegistroAlumnos extends javax.swing.JFrame {

    DefaultTableModel modelo=new DefaultTableModel();
    ArrayList<Alumno> listaAlumnos=new ArrayList<Alumno>();
    
    
    public RegistroAlumnos() {
        initComponents();
        this.setTitle("RESGISTRO DE ALUMNOS");
        this.setSize(720, 570);
        this.setLocationRelativeTo(null);
        modelo.addColumn("ESTUDIANTE");
        modelo.addColumn("CURSO");
        modelo.addColumn("AULA");
        
        refrescarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_registroalumnos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_estudiante = new javax.swing.JTextField();
        cbo_curso = new javax.swing.JComboBox<>();
        cbo_aula = new javax.swing.JComboBox<>();
        btn_agregar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_registroalumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Estudiante", "Curso", "Aula"
            }
        ));
        jScrollPane1.setViewportView(tbl_registroalumnos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 388, 112));

        jLabel1.setText("Estudiante: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel2.setText("Curso:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setText("Aula:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        getContentPane().add(txt_estudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 230, -1));

        cbo_curso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trigonometría", "Geometría", "Álgebra" }));
        cbo_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_cursoActionPerformed(evt);
            }
        });
        getContentPane().add(cbo_curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 170, -1));

        cbo_aula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101", "102", "103" }));
        getContentPane().add(cbo_aula, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        btn_agregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_agregar.setText("AGREGAR");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        btn_eliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void refrescarTabla(){
        
        while(modelo.getRowCount()>0){
            modelo.removeRow(0);
        }
        for (Alumno alumno : listaAlumnos){
            Object a[]=new Object[3];
            a[0]=alumno.getAlumno();
            a[1]=alumno.getCurso();
            a[2]=alumno.getAula();
            modelo.addRow(a);
        }
        tbl_registroalumnos.setModel(modelo);
    }
    
    private void cbo_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_cursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_cursoActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        
        try{
            
        Alumno alumno=new Alumno();
        alumno.setAlumno(txt_estudiante.getText());
        alumno.setCurso(cbo_curso.getSelectedItem().toString());
        alumno.setAula(Integer.parseInt(cbo_aula.getSelectedItem().toString()));
        listaAlumnos.add(alumno);
        refrescarTabla();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this,"ERROR AL AGREGAR ALUMNOS");
        }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        txt_estudiante.setText("");
        cbo_curso.setSelectedIndex(0);
        cbo_aula.setSelectedIndex(0);
    }//GEN-LAST:event_btn_eliminarActionPerformed
        
            
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JComboBox<String> cbo_aula;
    private javax.swing.JComboBox<String> cbo_curso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_registroalumnos;
    private javax.swing.JTextField txt_estudiante;
    // End of variables declaration//GEN-END:variables
}
